import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: '@kitiumai/cyclic-dependency-fixer',
  description: 'AI-powered tool to detect and fix circular dependencies in JavaScript/TypeScript projects. Features intelligent refactoring with Claude/GPT-4, codebase pattern learning, and context-aware fix recommendations',
  version: '3.0.1',
  category: 'plugin',
  tags: [
    'circular-dependency',
    'cyclic-dependency',
    'circular-dependencies',
    'cyclic-dependencies',
    'dependency-cycle',
    'import-cycle',
    'module-cycle',
    'dependency-analysis',
    'dependency-checker',
    'dependency-detector',
    'dependency-validator',
    'code-quality',
    'code-quality-tools',
    'refactoring',
    'refactoring-tools',
    'auto-refactor',
    'typescript',
    'typescript-tools',
    'javascript',
    'javascript-tools',
    'es6',
    'esm',
    'commonjs',
    'static-analysis',
    'code-analysis',
    'ast',
    'ast-parser',
    'abstract-syntax-tree',
    'codemod',
    'jscodeshift',
    'code-smell',
    'code-smell-detection',
    'technical-debt',
    'tech-debt',
    'architecture',
    'software-architecture',
    'clean-architecture',
    'dependency-graph',
    'module-dependency',
    'import-analysis',
    'import-resolver',
    'webpack',
    'webpack-plugin',
    'rollup',
    'rollup-plugin',
    'vite',
    'vite-plugin',
    'esbuild',
    'parcel',
    'bundler',
    'bundler-plugin',
    'build-tools',
    'build-optimization',
    'linting',
    'linter',
    'eslint',
    'eslint-plugin',
    'tslint',
    'automated-refactoring',
    'dependency-injection',
    'monorepo',
    'monorepo-tools',
    'nx',
    'nx-plugin',
    'lerna',
    'turborepo',
    'pnpm',
    'yarn',
    'npm',
    'nodejs',
    'node',
    'node-modules',
    'cli',
    'cli-tool',
    'command-line',
    'developer-tools',
    'devtools',
    'dev-tools',
    'developer-experience',
    'dx',
    'code-maintenance',
    'clean-code',
    'best-practices',
    'code-review',
    'ci-cd',
    'continuous-integration',
    'automation',
    'ai',
    'ai-powered',
    'ai-assistant',
    'ai-tools',
    'artificial-intelligence',
    'machine-learning',
    'llm',
    'large-language-model',
    'claude',
    'claude-ai',
    'gpt',
    'gpt-4',
    'chatgpt',
    'openai',
    'anthropic',
    'intelligent-refactoring',
    'smart-analysis',
    'context-aware',
    'pattern-learning',
    'fix-recommendations',
    'dry-run',
    'preview-changes',
    'sarif',
    'json-report',
    'github-actions',
    'gitlab-ci',
    'jenkins',
    'detection',
    'fixer',
    'resolver',
    'tree-shaking',
    'dead-code-elimination',
  ],
  types: [
    'rollup-plugin',
  ],
  links: {
    github: 'https://github.com/kitium-ai/cyclic-dependency-fixer',
    npm: 'https://www.npmjs.com/package/@kitiumai/cyclic-dependency-fixer',
  },
  stats: {
    downloads: {
      monthly: 202,
      weekly: 91,
    },
  },
})
