import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: '@nomaton/rollup-plugin-rusty-wasm',
  description: 'Rollup plugin to bundle wasm files generated by the Rust wasm-pack',
  version: '0.9.1',
  category: 'plugin',
  tags: [
    'rollup-plugin',
    'wasm',
  ],
  types: [
    'rollup-plugin',
  ],
  links: {
    github: 'https://github.com/nomaton/rollup-plugin-rusty-wasm',
    npm: 'https://www.npmjs.com/package/@nomaton/rollup-plugin-rusty-wasm',
  },
  stats: {
    downloads: {
      monthly: 17,
      weekly: 7,
    },
  },
})
