import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'unplugin-relay',
  description: 'A plugin for relay',
  version: '0.1.1',
  category: 'plugin',
  tags: [
    'astro',
    'astro-plugin',
    'astro-plugin-relay',
    'esbuild',
    'esbuild-plugin',
    'esbuild-plugin-relay',
    'farm',
    'farm-plugin',
    'farm-plugin-relay',
    'graphql',
    'graphql-relay',
    'nuxt',
    'nuxt-plugin',
    'nuxt-plugin-relay',
    'relay',
    'rolldown',
    'rolldown-plugin',
    'rolldown-plugin-relay',
    'rollup',
    'rollup-plugin',
    'rollup-plugin-relay',
    'rspack',
    'rspack-plugin',
    'rspack-plugin-relay',
    'typescript',
    'vite',
    'vite-plugin',
    'vite-plugin-relay',
    'webpack',
    'webpack-plugin',
    'webpack-plugin-relay',
  ],
  types: [
    'rollup-plugin',
  ],
  links: {
    github: 'https://github.com/PatrykWalach/unplugin-relay',
    npm: 'https://www.npmjs.com/package/unplugin-relay',
  },
  stats: {
    downloads: {
      monthly: 2934,
      weekly: 2551,
    },
  },
})
