import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'vite-asset-manifest',
  description: 'Vite 8 plugin that emits an asset manifest (manifest.json) mapping source filenames to hashed output paths. API-compatible port of rspack-manifest-plugin / webpack-manifest-plugin for backend asset pipelines (Rails, Phoenix, Django, Laravel, server-render',
  version: '0.1.1',
  category: 'plugin',
  tags: [
    'vite',
    'vite-plugin',
    'vite-8',
    'vite8',
    'rolldown',
    'rollup',
    'rollup-plugin',
    'manifest',
    'manifest-json',
    'asset-manifest',
    'asset-pipeline',
    'assets',
    'hash',
    'hashing',
    'fingerprint',
    'fingerprinting',
    'cache-busting',
    'webpack-manifest-plugin',
    'rspack-manifest-plugin',
    'webpack-manifest',
    'rspack-manifest',
    'rails',
    'phoenix',
    'django',
    'laravel',
    'ssr',
    'backend',
    'build-tool',
    'bundler',
    'esbuild',
    'esm',
    'typescript',
  ],
  types: [
    'rollup-plugin',
  ],
  links: {
    github: 'https://github.com/ilyasakin/vite-asset-manifest',
    npm: 'https://www.npmjs.com/package/vite-asset-manifest',
  },
  stats: {
    downloads: {
      monthly: 134,
      weekly: 41,
    },
  },
})
