import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@nomaton/rollup-plugin-rusty-wasm',
  description: 'Rollup plugin to bundle wasm files generated by the Rust wasm-pack',
  icon: 'logos:rollupjs',
  category: 'plugin',
  types: [
    'rollup-plugin',
  ],
  tags: [
    'rollup-plugin',
    'wasm',
  ],
  links: {
    github: 'https://github.com/nomaton/rollup-plugin-rusty-wasm',
    npm: 'https://www.npmjs.com/package/@nomaton/rollup-plugin-rusty-wasm',
    website: 'https://github.com/nomaton/rollup-plugin-rusty-wasm#readme',
  },
  source: {
    github: 'nomaton/rollup-plugin-rusty-wasm',
    npm: '@nomaton/rollup-plugin-rusty-wasm',
  },
  stats: {
    stars: 0,
    downloads: {
      monthly: 17,
      weekly: 2,
    },
  },
})
