import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'async-browser-context',
  description: 'AsyncLocalStorage and the TC39 AsyncContext API (Variable, Snapshot) for browsers. The context stays through await, promises, timers, events and generators. A Babel preset and a Vite plugin transform async functions. On Node.js, the package uses the nativ',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'asynclocalstorage',
    'async-local-storage',
    'asynccontext',
    'async-context',
    'async-context-polyfill',
    'tc39',
    'proposal-async-context',
    'polyfill',
    'browser',
    'context',
    'context-propagation',
    'continuation-local-storage',
    'cls',
    'async-hooks',
    'zone',
    'zone.js',
    'request-context',
    'request-id',
    'correlation-id',
    'tracing',
    'opentelemetry',
    'logging',
    'await',
    'promise',
    'babel-preset',
    'babel-plugin',
    'vite-plugin',
    'vite',
    'react',
  ],
  links: {
    github: 'https://github.com/mark1russell7/AsyncBrowserContext',
    npm: 'https://www.npmjs.com/package/async-browser-context',
    website: 'https://mark1russell7.github.io/AsyncBrowserContext/',
  },
  source: {
    github: 'mark1russell7/AsyncBrowserContext',
    npm: 'async-browser-context',
  },
})
