import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@castlenine/vite-plugin-console-stripper',
  description: 'A Vite plugin that removes console calls from your production build and keeps the ones you still need (by default console.error, console.warn, console.info and console.clear). It works on your own code and on dependencies, and supports ignore comments, pa',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'analog',
    'angular',
    'astro',
    'build',
    'console',
    'console-log',
    'console.log',
    'debug',
    'drop-console',
    'drop_console',
    'logging',
    'mdx',
    'plugin',
    'preact',
    'production',
    'react',
    'reactjs',
    'remove-console',
    'remove-console-log',
    'solid',
    'solidjs',
    'sourcemap',
    'strip',
    'strip-console',
    'strip-console-log',
    'svelte',
    'sveltekit',
    'transform-remove-console',
    'typescript',
    'vite',
    'vite-plugin',
    'vitejs',
    'vue',
    'vuejs',
  ],
  links: {
    github: 'https://github.com/Castlenine/vite-plugin-console-stripper',
    npm: 'https://www.npmjs.com/package/@castlenine/vite-plugin-console-stripper',
    website: 'https://github.com/Castlenine/vite-plugin-console-stripper',
  },
  source: {
    github: 'Castlenine/vite-plugin-console-stripper',
    npm: '@castlenine/vite-plugin-console-stripper',
  },
})
