import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@castlenine/vite-plugin-remove-attribute',
  description: 'Vite plugin that removes specified attributes, such as \'data-testid\' used in testing. Options cover file extensions, attributes, and folders and files to ignore.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'angular',
    'astro',
    'attribute',
    'attributes',
    'cypress',
    'data-cy',
    'data-qa',
    'data-test',
    'data-test-id',
    'data-testid',
    'html',
    'jsx',
    'lit',
    'playwright',
    'preact',
    'qwik',
    'react',
    'reactjs',
    'remove-attribute',
    'remove-attributes',
    'remove-data-testid',
    'solid',
    'solidjs',
    'strip-attributes',
    'svelte',
    'sveltekit',
    'test-id',
    'testid',
    'testing-library',
    'tsx',
    'vite',
    'vite-plugin',
    'vue',
    'vuejs',
  ],
  links: {
    github: 'https://github.com/Castlenine/vite-plugin-remove-attribute',
    npm: 'https://www.npmjs.com/package/@castlenine/vite-plugin-remove-attribute',
    website: 'https://github.com/Castlenine/vite-plugin-remove-attribute',
  },
  source: {
    github: 'Castlenine/vite-plugin-remove-attribute',
    npm: '@castlenine/vite-plugin-remove-attribute',
  },
  stats: {
    stars: 4,
    downloads: {
      monthly: 0,
      weekly: 0,
    },
  },
})
