import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@denkwerk/favicon-generator',
  description: 'Generate favicons, touch icons, a web app manifest and browserconfig.xml from an SVG or a Figma node. CLI and Node.js API; also available as a Nuxt module and a Vite, Rollup, Rolldown, webpack and Rspack plugin',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'favicon',
    'favicon-generator',
    'favicons',
    'favicon.ico',
    'apple-touch-icon',
    'web-app-manifest',
    'manifest',
    'pwa',
    'svg',
    'figma',
    'icons',
    'cli',
    'rust',
    'generator',
    'browserconfig',
    'head-tags',
    'nuxt',
    'nuxt-module',
    'vite',
    'vite-plugin',
    'rollup',
    'rollup-plugin',
    'rolldown',
    'rolldown-plugin',
    'tsdown',
    'webpack',
    'webpack-plugin',
    'rspack',
    'rspack-plugin',
    'unplugin',
  ],
  links: {
    github: 'https://github.com/denkwerk/favicon-generator',
    npm: 'https://www.npmjs.com/package/@denkwerk/favicon-generator',
    website: 'https://github.com/denkwerk/favicon-generator/tree/main/packages/favicon-generator#readme',
  },
  source: {
    github: 'denkwerk/favicon-generator',
    npm: '@denkwerk/favicon-generator',
  },
})
