import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@denkwerk/nuxt-favicon-generator',
  description: 'Nuxt module that generates favicons, touch icons and a web app manifest from an SVG or a Figma node, and adds the head tags',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'favicon',
    'favicon-generator',
    'favicons',
    'favicon.ico',
    'apple-touch-icon',
    'web-app-manifest',
    'manifest',
    'pwa',
    'svg',
    'figma',
    'icons',
    'nuxt',
    'nuxt-module',
    'nuxt3',
    'nuxt4',
    'nitro',
    'vite',
    'vite-plugin',
    'rollup',
    'rollup-plugin',
    'rolldown',
    'rolldown-plugin',
    'tsdown',
    'webpack',
    'webpack-plugin',
    'rspack',
    'rspack-plugin',
    'unplugin',
  ],
  links: {
    github: 'https://github.com/denkwerk/favicon-generator',
    npm: 'https://www.npmjs.com/package/@denkwerk/nuxt-favicon-generator',
    website: 'https://github.com/denkwerk/favicon-generator/tree/main/packages/nuxt-favicon-generator#readme',
  },
  source: {
    github: 'denkwerk/favicon-generator',
    npm: '@denkwerk/nuxt-favicon-generator',
  },
})
