import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'ide-byebye',
  description: 'Dev plugin for Vite / webpack / rspack / rsbuild / esbuild / Farm, Next.js (Turbopack + webpack) and the Angular CLI: ⌘-click any rendered element (React, Vue, Svelte, Solid, Angular; Next.js, Nuxt, SvelteKit), describe the change in plain words, and hand',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite',
    'vite-plugin',
    'webpack',
    'rspack',
    'rsbuild',
    'esbuild',
    'farm',
    'turbopack',
    'mako',
    'unplugin',
    'code-inspector',
    'vue',
    'react',
    'claude',
    'codex',
    'cursor',
    'grok',
    'grok-build',
    'ai',
    'devtools',
    'intent',
    'deeplink',
    'rrweb',
    'nextjs',
    'next',
    'nuxt',
    'svelte',
    'sveltekit',
    'solid',
    'solid-js',
    'angular',
    'preact',
  ],
  links: {
    github: 'https://github.com/bo-516/ide-byebye',
    npm: 'https://www.npmjs.com/package/ide-byebye',
    website: 'https://github.com/bo-516/ide-byebye#readme',
  },
  source: {
    github: 'bo-516/ide-byebye',
    npm: 'ide-byebye',
  },
  stats: {
    stars: 7,
    downloads: {
      monthly: 1697,
      weekly: 323,
    },
  },
})
