import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@inlang/paraglide-js',
  description: '[![NPM Downloads](https://img.shields.io/npm/dw/%40inlang%2Fparaglide-js?logo=npm&logoColor=red&label=npm%20downloads)](https://www.npmjs.com/package/@inlang/paraglide-js) [![GitHub Issues](https://img.shields.io/github/issues-closed/opral/paraglide-js?lo',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'inlang',
    'paraglide',
    'javascript i18n',
    'i18n',
    'l10n',
    'translation',
    'internationalization',
    'svelte',
    'localization',
    'react',
    'vue',
    'angular',
    'nextjs',
    'react router',
    'next i18n',
    'astro',
    'astro i18n',
    'solid',
    'solidstart',
    'tanstack',
    'tanstack router',
    'tanstack start',
    'rolldown',
    'vite',
    'vite-plugin',
    'rollup-plugin',
  ],
  source: {
    github: 'opral/paraglide-js',
    npm: '@inlang/paraglide-js',
  },
  links: {
    github: 'https://github.com/opral/paraglide-js',
    npm: 'https://www.npmjs.com/package/@inlang/paraglide-js',
    website: 'https://paraglidejs.com',
  },
  stats: {
    stars: 695,
    downloads: {
      monthly: 1895581,
      weekly: 431150,
    },
  },
})
