import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'react-icons-sprite',
  description: 'A lightweight Vite, Rsbuild and Webpack plugin for popular icon libraries that builds a single SVG sprite and rewrites icons to <use>, reducing bundle size and runtime overhead.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite',
    'vite-plugin',
    'webpack',
    'webpack-plugin',
    'rsbuild',
    'rsbuild-plugin',
    'esbuild',
    'rollup',
    'rolldown',
    'react-icons',
    'lucide-react',
    '@radix-ui/react-icons',
    '@heroicons/react',
    '@tabler/icons-react',
    'phosphor-react',
    '@phosphor-icons/react',
    'react-feather',
    'react-bootstrap-icons',
    'grommet-icons',
    '@remixicon/react',
    'devicons-react',
    '@fortawesome/react-fontawesome',
    '@fortawesome/free-solid-svg-icons',
    '@mui/icons-material',
    '@carbon/icons-react',
    '@ant-design/icons',
    '@fluentui/react-icons',
    '@primer/octicons-react',
    '@hugeicons/react',
    '@hugeicons/core-free-icons',
    'react',
    'icons',
    'svg',
    'svg-sprite',
    'spritesheet',
    'icon-sprite',
  ],
  links: {
    github: 'https://github.com/jurerotar/react-icons-sprite',
    npm: 'https://www.npmjs.com/package/react-icons-sprite',
    website: 'https://github.com/jurerotar/react-icons-sprite#readme',
  },
  source: {
    github: 'jurerotar/react-icons-sprite',
    npm: 'react-icons-sprite',
  },
  stats: {
    stars: 10,
    downloads: {
      monthly: 3543,
      weekly: 460,
    },
  },
})
