import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'squeezit',
  description: 'Lossless image optimizer CLI, JS/TS API, and bundler plugins for PNG, JPEG, GIF, WebP, SVG, AVIF, HEIC, JXL, ICO, BMP, and more.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'squeezit',
    'image',
    'images',
    'image-compression',
    'image-optimizer',
    'image-optimization',
    'lossless',
    'lossless-compression',
    'compress-images',
    'optimize-images',
    'cli',
    'javascript',
    'typescript',
    'vite-plugin',
    'webpack-plugin',
    'rollup-plugin',
    'parcel-plugin',
    'astro-integration',
    'esbuild-plugin',
    'gulp-plugin',
    'grunt-plugin',
    'nextjs',
    'png',
    'jpeg',
    'webp',
    'avif',
    'heic',
    'svg',
  ],
  links: {
    github: 'https://github.com/ghaschel/squeezit',
    npm: 'https://www.npmjs.com/package/squeezit',
    website: 'https://github.com/ghaschel/squeezit#readme',
  },
  source: {
    github: 'ghaschel/squeezit',
    npm: 'squeezit',
  },
  stats: {
    stars: 1,
    downloads: {
      monthly: 728,
      weekly: 15,
    },
  },
})
