import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'tailwindcss-obfuscator',
  description: 'Tailwind CSS class mangler & obfuscator — rename utility classes (bg-blue-500 → tw-a) at build time. Vite, Webpack, Rollup, esbuild, Next.js, Nuxt, SvelteKit, Astro, Solid, Qwik, React Router 7, TanStack Router. Tailwind v3 + v4. Cuts CSS bundle 30–60% an',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'tailwindcss',
    'tailwind',
    'tailwind-css',
    'obfuscator',
    'obfuscation',
    'mangle',
    'mangler',
    'tailwindcss-mangle',
    'tailwindcss-mangler',
    'tailwind-mangle',
    'tailwind-mangler',
    'tailwindcss-mangle-alternative',
    'class-mangler',
    'class-name-mangler',
    'css-class-mangler',
    'tailwind-class-mangler',
    'tailwind-class-shortener',
    'tailwind-css-mangler',
    'minify',
    'css',
    'css-minifier',
    'vite',
    'vite-plugin',
    'webpack',
    'webpack-plugin',
    'rollup',
    'rollup-plugin',
    'esbuild',
    'esbuild-plugin',
    'rspack',
    'rspack-plugin',
    'farm',
    'farm-plugin',
    'nextjs',
    'next',
    'nuxt',
    'sveltekit',
    'svelte',
    'astro',
    'solid',
    'qwik',
    'react-router',
    'remix',
    'tanstack-router',
    'tanstack',
    'shadcn',
    'shadcn-ui',
    'cva',
    'class-variance-authority',
    'tailwind-v3',
    'tailwind-v4',
    'typescript',
    'unplugin',
  ],
  source: {
    github: 'josedacosta/tailwindcss-obfuscator',
    npm: 'tailwindcss-obfuscator',
  },
  links: {
    github: 'https://github.com/josedacosta/tailwindcss-obfuscator',
    npm: 'https://www.npmjs.com/package/tailwindcss-obfuscator',
    website: 'https://github.com/josedacosta/tailwindcss-obfuscator#readme',
  },
  stats: {
    stars: 0,
    downloads: {
      monthly: 563,
      weekly: 109,
    },
  },
})
