import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-optimize-css-modules',
  description: 'Mangles the classnames generated by postcss-modules in vite',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite',
    'vite-plugin',
    'css-modules',
    'css',
    'minify',
  ],
  source: {
    github: 'simonwep/vite-plugin-optimize-css-modules',
    npm: 'vite-plugin-optimize-css-modules',
  },
  links: {
    github: 'https://github.com/simonwep/vite-plugin-optimize-css-modules',
    npm: 'https://www.npmjs.com/package/vite-plugin-optimize-css-modules',
    website: 'https://github.com/simonwep/vite-plugin-optimize-css-modules',
  },
  stats: {
    stars: 48,
    downloads: {
      monthly: 57861,
      weekly: 13655,
    },
  },
})
