import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-image-react',
  description: 'Content-aware, device-adaptive image optimizer for React. Works with Vite and Next.js. Auto-converts to AVIF/WebP/JPEG with SSIM auto-tune, face detection, SVGO, and device-tier delivery. Built by @ezitounioussama at gotodev.ma.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'image',
    'optimizer',
    'optimization',
    'compression',
    'vite',
    'vite-plugin',
    'nextjs',
    'next-plugin',
    'react',
    'react-component',
    'image-optimization',
    'image-compression',
    'webp',
    'avif',
    'jpeg',
    'png',
    'svg',
    'svgo',
    'sharp',
    'responsive-images',
    'lazy-loading',
    'blur-up',
    'placeholder',
    'ssim',
    'content-aware',
    'perceptual',
    'saliency',
    'face-detection',
    'device-adaptive',
    'performance',
    'core-web-vitals',
    'lcp',
    'cls',
    'image-loader',
    'picture',
    'srcset',
  ],
  source: {
    github: 'ezitounioussama/vite-image-react',
    npm: 'vite-image-react',
  },
  links: {
    github: 'https://github.com/ezitounioussama/vite-image-react',
    npm: 'https://www.npmjs.com/package/vite-image-react',
    website: 'https://github.com/ezitounioussama/vite-image-react#readme',
  },
  stats: {
    stars: 2,
    downloads: {
      monthly: 41,
      weekly: 13,
    },
  },
})
