import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-sri-gen',
  description: 'A Vite plugin to auto-generate Subresource Integrity (SRI) hashes.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite',
    'subresource',
    'integrity',
    'sri',
    'content',
    'security',
    'policy',
    'csp',
    'plugin',
    'vite-plugin',
    'vite-plugin-sri',
    'vite-sri',
    'subresource-integrity',
    'integrity-hash',
    'sha256',
    'sha384',
    'sha512',
    'modulepreload',
    'ssr',
    'ssg',
    'spa',
    'mpa',
    'prerender',
    'cdn',
    'web-security',
    'content-security-policy',
  ],
  links: {
    github: 'https://github.com/rbonestell/vite-plugin-sri-gen',
    npm: 'https://www.npmjs.com/package/vite-plugin-sri-gen',
    website: 'https://rbonestell.com/vite-plugin-sri-gen/',
  },
  source: {
    github: 'rbonestell/vite-plugin-sri-gen',
    npm: 'vite-plugin-sri-gen',
  },
  stats: {
    stars: 24,
    downloads: {
      monthly: 35614,
      weekly: 7988,
    },
  },
})
