import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-typed-router',
  description: 'Provide autocompletion for pages route names generated by vite-plugin-pages router',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite-plugin vue typed pages',
    'vite-plugin vue router typed',
    'vite-plugin typed router',
    'vite-plugin safe router',
    'vite-plugin typed routes',
    'vite-plugin generate route types',
    'vite-plugin pages',
    'vite-plugin vue',
    'vite-plugin',
  ],
  source: {
    github: 'victorgarciaesgi/vite-plugin-typed-router',
    npm: 'vite-plugin-typed-router',
  },
  links: {
    github: 'https://github.com/victorgarciaesgi/vite-plugin-typed-router',
    npm: 'https://www.npmjs.com/package/vite-plugin-typed-router',
    website: 'https://github.com/victorgarciaesgi/vite-plugin-typed-router#readme',
  },
  stats: {
    stars: 3,
    downloads: {
      monthly: 14,
      weekly: 1,
    },
  },
})
