import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-plugins-library',
  description: 'A curated collection of production-ready custom Vite plugins and standalone CLI logger utilities inspired by enterprise Vite configurations.',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'vite',
    'vite-plugin',
    'vite-plugins',
    'vitejs',
    'vite-config',
    'build-tools',
    'frontend-tools',
    'rollup-plugin',
    'proxy',
    'dev-proxy',
    'redirects',
    'netlify',
    'vercel',
    'nginx',
    'env-loader',
    'env-vars',
    'environment-variables',
    'env-validator',
    'env-schema',
    'compression',
    'gzip',
    'brotli',
    'seo',
    'html-meta',
    'open-graph',
    'twitter-cards',
    'favicon',
    'api-mock',
    'mock-server',
    'mock-api',
    'code-split',
    'code-splitting',
    'cdn',
    'image-cdn',
    'asset-management',
    'postcss',
    'tailwind',
    'tailwind-v4',
    'shadow-dom',
    'web-components',
    'jsx',
    'js-as-jsx',
    'esbuild',
    'oxc',
    'alias',
    'path-alias',
    'logger',
    'cli-logger',
    'logging',
    'ansi-logger',
    'terminal-colors',
    'utility',
    'react',
    'typescript',
    'security-headers',
    'csp',
    'banner-notice',
    'svg-sprite',
    'svg-icons',
    'resource-hints',
    'modulepreload',
    'cache-cleaner',
    'cache-purge',
    'build-performance',
    'build-metrics',
    'build-scorer',
    'build-score',
    'build-audit',
    'build-health',
    'quality-score',
  ],
  links: {
    github: 'https://github.com/yathink3/vite-plugins-library',
    npm: 'https://www.npmjs.com/package/vite-plugins-library',
    website: 'https://github.com/yathink3/vite-plugins-library#readme',
  },
  source: {
    github: 'yathink3/vite-plugins-library',
    npm: 'vite-plugins-library',
  },
  stats: {
    stars: 1,
    downloads: {
      monthly: 3055,
      weekly: 51,
    },
  },
})
