import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: '@xtreat/solid-iconify',
  description: 'A reactive and first class native Solid Iconify icon component',
  icon: 'logos:vite-icon',
  category: 'plugin',
  types: [
    'vite-plugin',
  ],
  tags: [
    'solidjs',
    'solid.js',
    'solid',
    'iconify',
    'iconify icon',
    'icon',
    'svg',
    'svg icon',
    'reactive icon',
    'ssr',
    'ssr-ready',
    'typescript',
    'ts',
    'js',
    'esm',
    'jsx',
    'component',
    'ui',
    'ui component',
    'icon component',
    'icon library',
    'icon set',
    'icon pack',
    'icon collection',
    'icon bundle',
    'icon system',
    'icon loader',
    'dynamic icon',
    'custom icon',
    'open source',
    'npm package',
    'vite',
    'vite-plugin',
    'biome',
    'lru cache',
    'cache',
    'svg sanitizer',
    'xss',
    'api',
    'api client',
    'frontend',
    'web',
    'web component',
    'modern js',
    'zero dependencies',
    'minimal',
    'fast',
    'high performance',
    'reactive',
    'configurable',
    'customizable',
    'ssg',
    'server-side rendering',
    'browser',
    'npm',
    'library',
  ],
  links: {
    github: 'https://github.com/xandertreat/solid-iconify',
    npm: 'https://www.npmjs.com/package/@xtreat/solid-iconify',
    website: 'https://github.com/xandertreat/solid-iconify#readme',
  },
  source: {
    github: 'xandertreat/solid-iconify',
    npm: '@xtreat/solid-iconify',
  },
  stats: {
    stars: 2,
    downloads: {
      monthly: 48,
      weekly: 30,
    },
  },
})
