import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: '@dxtmisha/d1',
  description: 'Vue 3 design system component library (DXT-UI D1) with comprehensive UI components, design tokens, SCSS mixins, and Vite plugin',
  version: '0.113.0',
  category: 'plugin',
  tags: [
    'vue',
    'vue3',
    'd1',
    'dxt',
    'dxt-ui',
    'ui-library',
    'component-library',
    'design-system',
    'typescript',
    'scss',
    'design-tokens',
    'vite-plugin',
    'button',
    'input',
    'modal',
    'table',
    'select',
    'form',
    'tabs',
    'menu',
    'list',
    'checkbox',
    'radio',
    'switch',
    'tooltip',
    'dialog',
    'snackbar',
    'pagination',
    'aria',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/dxtmisha/dxt-ui',
    npm: 'https://www.npmjs.com/package/@dxtmisha/d1',
  },
  stats: {
    downloads: {
      monthly: 652,
      weekly: 41,
    },
  },
})
