import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: '@importable/document',
  description: 'Import documents with strong typing based on import attributes',
  version: '0.1.0',
  category: 'plugin',
  tags: [
    'assert',
    'asserts',
    'assertions',
    'attribute',
    'attributes',
    'doc',
    'document',
    'dom',
    'file',
    'files',
    'html',
    'import',
    'importable',
    'importable-plugin',
    'imports',
    'node',
    'plugin',
    'javascript',
    'js',
    'jsconfig',
    'rollup',
    'rollup-plugin',
    'strong',
    'ts',
    'tsconfig',
    'type',
    'typed',
    'types',
    'typescript',
    'typescript-plugin',
    'typing',
    'vite',
    'vite-plugin',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/importables/importable',
    npm: 'https://www.npmjs.com/package/@importable/document',
  },
  stats: {
    downloads: {
      monthly: 13,
      weekly: 5,
    },
  },
})
