import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'quantcss',
  description: 'Modern CSS framework',
  version: '1.0.2',
  category: 'plugin',
  tags: [
    'quantcss',
    'css',
    'css-framework',
    'runtime-css',
    'dynamic-css',
    'utility-first',
    'utility-css',
    'atomic-css',
    'css-engine',
    'design-system',
    'vite',
    'vite-plugin',
    'tailwind-alternative',
    'unocss-alternative',
    'frontend',
    'ui',
    'responsive',
    'theming',
    'modern-css',
    'javascript-framework',
    'developer-tools',
    'css-runtime',
    'hmr',
    'ssr',
    'plugin-system',
    'react',
    'vue',
    'angular',
    'web-development',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/NdombeRafa33/Quantcss',
    npm: 'https://www.npmjs.com/package/quantcss',
  },
  stats: {
    downloads: {
      monthly: 26,
      weekly: 1,
    },
  },
})
