import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'react-icons-sprite',
  description: 'A lightweight Vite, Rsbuild and Webpack plugin for popular icon libraries that builds a single SVG sprite and rewrites icons to <use>, reducing bundle size and runtime overhead.',
  version: '1.2.0',
  category: 'plugin',
  tags: [
    'vite',
    'vite-plugin',
    'webpack',
    'webpack-plugin',
    'rsbuild',
    'rsbuild-plugin',
    'esbuild',
    'rollup',
    'rolldown',
    'react-icons',
    'lucide-react',
    '@radix-ui/react-icons',
    '@heroicons/react',
    '@tabler/icons-react',
    'phosphor-react',
    '@phosphor-icons/react',
    'react-feather',
    'react-bootstrap-icons',
    'grommet-icons',
    '@remixicon/react',
    'devicons-react',
    '@fortawesome/react-fontawesome',
    '@fortawesome/free-solid-svg-icons',
    '@mui/icons-material',
    '@carbon/icons-react',
    '@ant-design/icons',
    '@fluentui/react-icons',
    '@primer/octicons-react',
    '@hugeicons/react',
    '@hugeicons/core-free-icons',
    'react',
    'icons',
    'svg',
    'svg-sprite',
    'spritesheet',
    'icon-sprite',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/jurerotar/react-icons-sprite',
    npm: 'https://www.npmjs.com/package/react-icons-sprite',
  },
  stats: {
    downloads: {
      monthly: 4028,
      weekly: 1135,
    },
  },
})
