import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'svger-cli',
  description: 'Enterprise-grade SVG to component converter with advanced plugin system, visual diff testing, and official framework integrations. Supporting React, React Native, Vue, Angular, Svelte, Solid, Lit, Preact & Vanilla. Features TypeScript, HMR, optimization p',
  version: '4.0.9',
  category: 'plugin',
  tags: [
    'svg',
    'react',
    'vue',
    'angular',
    'svelte',
    'solid',
    'preact',
    'lit',
    'cli',
    'components',
    'typescript',
    'zero-dependency',
    'performance',
    'design-system',
    'responsive',
    'enterprise',
    'batch-processing',
    'icon-generation',
    'frontend-tooling',
    'webpack',
    'webpack-plugin',
    'webpack-loader',
    'vite',
    'vite-plugin',
    'rollup',
    'rollup-plugin',
    'babel',
    'babel-plugin',
    'babel-transform',
    'nextjs',
    'next-js',
    'jest',
    'jest-preset',
    'jest-transformer',
    'build-tools',
    'bundler',
    'hmr',
    'hot-module-replacement',
    'web-components',
    'component-library',
    'svg-optimization',
    'framework-agnostic',
    'developer-tools',
    'build-tools',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/faezemohades/svger-cli',
    npm: 'https://www.npmjs.com/package/svger-cli',
  },
  stats: {
    downloads: {
      monthly: 242,
      weekly: 43,
    },
  },
})
