import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'transform-to-tailwindcss',
  description: '🎨 Revolutionary CSS-to-TailwindCSS migration tool with surgical precision. Transform legacy stylesheets to utility-first classes instantly across Vue, React, Svelte, and Astro projects.',
  version: '0.0.56',
  category: 'plugin',
  tags: [
    'transform-to-tailwindcss',
    'tailwindcss',
    'css-transform',
    'utility-first',
    'css-migration',
    'vue',
    'react',
    'svelte',
    'astro',
    'vite-plugin',
    'webpack-plugin',
    'rollup-plugin',
    'esbuild-plugin',
    'css-preprocessor',
    'sass',
    'less',
    'stylus',
    'performance',
    'optimization',
    'developer-tools',
    'build-tools',
    'css-to-tailwind',
    'legacy-css',
    'modern-css',
    'automated-migration',
    'code-transformation',
    'frontend-tooling',
    'css-utilities',
    'responsive-design',
    'atomic-css',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/Simon-He95/transformToTailwindcss',
    npm: 'https://www.npmjs.com/package/transform-to-tailwindcss',
  },
  stats: {
    downloads: {
      monthly: 325,
      weekly: 74,
    },
  },
})
