import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-singlefile-compression',
  description: 'Compress all assets and embeds them into dist/index.html, making it convenient to share as a single HTML file.',
  version: '2.4.9',
  category: 'plugin',
  tags: [
    'vite-plugin',
    'vite',
    'plugin',
    'SFA',
    'single-file',
    'singlefile',
    'single',
    'compression',
    'compress',
    'compressionstream',
    'decompress',
    'decompression',
    'decompressionstream',
    'compression streams api',
    'compression streams',
    'gzip',
    'deflate',
    'deflate-raw',
    'deflateraw',
    'br',
    'brotli',
    'zstd',
    'zlib',
    'inline',
    'embed',
    'bundle',
    'bundler',
    'frontend',
    'front-end',
    'framework',
    'hmr',
    'dev-server',
    'build-tool',
    'html',
    'htm',
    'htmlmin',
    'js',
    'javascript',
    'css',
    'class',
    'rolldown',
    'rolldown-vite',
    'rollup',
    'min',
    'minification',
    'minifier',
    'minify',
    'optimize',
    'optimizer',
    'pack',
    'packer',
    'vite-plugin-singlefile',
    'vite-plugin-compression',
    'vite-plugin-compression2',
    'html-minifier-terser',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/bddjr/vite-plugin-singlefile-compression',
    npm: 'https://www.npmjs.com/package/vite-plugin-singlefile-compression',
  },
  stats: {
    downloads: {
      monthly: 1764,
      weekly: 328,
    },
  },
})
