import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'vite-upload-assets-oss',
  description: '🚀 A powerful Vite plugin that automatically uploads media assets to multiple cloud storage providers (OSS, COS, S3, OBS) and replaces references with CDN URLs. Supports multiple import methods, caching, and concurrent uploads. | 一个强大的Vite插件，自动将媒体资源上传到多个云',
  version: '1.1.0',
  category: 'plugin',
  tags: [
    'vite',
    'vite-plugin',
    'oss',
    'cos',
    's3',
    'obs',
    'alibaba-cloud',
    'tencent-cloud',
    'aws',
    'huawei-cloud',
    'multi-cloud',
    'cdn',
    'assets',
    'upload',
    'media',
    'optimization',
    'webpack',
    'rollup',
    'build-tool',
    '阿里云',
    '腾讯云',
    '华为云',
    '对象存储',
    '多云存储',
    '资源上传',
    'CDN加速',
    '媒体资源',
    '前端构建',
    '静态资源',
    '云存储',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/zhangnuli/vite-upload-assets-oss',
    npm: 'https://www.npmjs.com/package/vite-upload-assets-oss',
  },
  stats: {
    downloads: {
      monthly: 32,
      weekly: 9,
    },
  },
})
