import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-optimize-css-modules',
  description: 'Mangles the classnames generated by postcss-modules in vite',
  version: '1.4.0',
  category: 'plugin',
  tags: [
    'vite',
    'vite-plugin',
    'css-modules',
    'css',
    'minify',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/simonwep/vite-plugin-optimize-css-modules',
    npm: 'https://www.npmjs.com/package/vite-plugin-optimize-css-modules',
  },
  stats: {
    downloads: {
      monthly: 54360,
      weekly: 15166,
    },
  },
})
