import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'vite-plugin-typed-router',
  description: 'Provide autocompletion for pages route names generated by vite-plugin-pages router',
  version: '0.0.1',
  category: 'plugin',
  tags: [
    'vite-plugin vue typed pages',
    'vite-plugin vue router typed',
    'vite-plugin typed router',
    'vite-plugin safe router',
    'vite-plugin typed routes',
    'vite-plugin generate route types',
    'vite-plugin pages',
    'vite-plugin vue',
    'vite-plugin',
  ],
  types: [
    'vite-plugin',
  ],
  links: {
    github: 'https://github.com/victorgarciaesgi/vite-plugin-typed-router',
    npm: 'https://www.npmjs.com/package/vite-plugin-typed-router',
  },
  stats: {
    downloads: {
      monthly: 19,
      weekly: 4,
    },
  },
})
