import { defineProjectMeta } from '@vuejs-community/schema'

export default defineProjectMeta({
  name: 'unplugin-relay',
  description: 'A plugin for relay',
  icon: 'icon:dark-unplugin',
  category: 'plugin',
  types: [
    'unplugin',
  ],
  tags: [
    'astro',
    'astro-plugin',
    'astro-plugin-relay',
    'esbuild',
    'esbuild-plugin',
    'esbuild-plugin-relay',
    'farm',
    'farm-plugin',
    'farm-plugin-relay',
    'graphql',
    'graphql-relay',
    'nuxt',
    'nuxt-plugin',
    'nuxt-plugin-relay',
    'relay',
    'rolldown',
    'rolldown-plugin',
    'rolldown-plugin-relay',
    'rollup',
    'rollup-plugin',
    'rollup-plugin-relay',
    'rspack',
    'rspack-plugin',
    'rspack-plugin-relay',
    'typescript',
    'vite',
    'vite-plugin',
    'vite-plugin-relay',
    'webpack',
    'webpack-plugin',
    'webpack-plugin-relay',
  ],
  source: {
    github: 'PatrykWalach/unplugin-relay',
    npm: 'unplugin-relay',
  },
  links: {
    github: 'https://github.com/PatrykWalach/unplugin-relay',
    npm: 'https://www.npmjs.com/package/unplugin-relay',
    website: 'https://github.com/PatrykWalach/unplugin-relay#readme',
  },
  stats: {
    stars: 1,
    downloads: {
      monthly: 6771,
      weekly: 2582,
    },
  },
})
