import { defineProjectMeta } from '@vue-community/schema'

export default defineProjectMeta({
  name: 'byte-snap',
  description: 'A byte counter for your build. Snap before, snap after, see the delta.',
  version: '1.1.4',
  category: 'plugin',
  tags: [
    'size',
    'bundle-size',
    'bundle',
    'bundler',
    'filesize',
    'file-size',
    'diff',
    'snapshot',
    'measure',
    'bytes',
    'byte-counter',
    'build',
    'build-size',
    'dist-size',
    'output-size',
    'size-check',
    'size-limit',
    'performance',
    'minify',
    'compression',
    'gzip',
    'brotli',
    'vite-plugin',
    'rollup-plugin',
    'webpack-plugin',
    'esbuild-plugin',
    'rspack-plugin',
    'rolldown-plugin',
    'farm-plugin',
    'unplugin',
  ],
  types: [
    'rolldown-plugin',
  ],
  links: {
    github: 'https://github.com/jayf0x/byte-snap',
    npm: 'https://www.npmjs.com/package/byte-snap',
  },
  stats: {
    downloads: {
      monthly: 156,
      weekly: 7,
    },
  },
})
